"""empty message

Revision ID: 5fe824a926fd
Revises: 74565a7569a9
Create Date: 2023-06-15 15:49:52.887087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe824a926fd'
down_revision = '74565a7569a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_table', schema=None) as batch_op:
        batch_op.drop_constraint('show_venue_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('show_venue_id_fkey', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
